### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by 2xrb** [PixelatedW/mineminenomi#178]
Hey, i got a suggestion on what you could add in the next update, Mochi Mochi no Mi would be a good devil fruit to make, and another thing to add in would be the viver card, and to make a sweets biome from big moms island, and it would also be cool if added minks, skypian race for different move set, and last of all maybe mounts like aces boat and maybe skypean rocket shoes to get around faster

**Comment by FGpisces** [comment]
We're not adding any fruits in the next update, and we're eventually add all devil fruits, not just Mochi.
Vivre cards are already in the mod, put a paper in a crafting table and you'll get your vivre card.
More races will be added eventually, but most likely not skypieans, since they aren't special at all and have nothing interesting going for them.
We'll also add some vehicles in the future, but right now the Yagara bulls are a faster and better option than normal boats, so new vehicles aren't our priority.

**Comment by 2xrb** [comment]
thank you

**Comment by adrian200145** [comment]
> We're not adding any fruits in the next update, and we're eventually add all devil fruits, not just Mochi.
> Vivre cards are already in the mod, put a paper in a crafting table and you'll get your vivre card.
> More races will be added eventually, but most likely not skypieans, since they aren't special at all and have nothing interesting going for them.
> We'll also add some vehicles in the future, but right now the Yagara bulls are a faster and better option than normal boats, so new vehicles aren't our priority.

About this what I think they could be cool for is to create skyisland biomes so you could have an ennel bossfight, if not, with the help of the comunity skypea and shandia could be built, and added as a biome.

**Comment by FGpisces** [comment]
Cleaning up threads, bosses are implemented in the latest update and Sky islands along with Enel will be implemented soon as well.
