### ISSUE TITLE
Mobs don't drop anything for me

### ISSUE THREAD

**Issue by Burningcory** [PixelatedW/mineminenomi#208]
Idk exactly what the loots drop rates are but from what i understand you can get like guns, maces and capes from the mobs of the mod, but i have never gotten a single drop and i feel like i've invested at least 30-40hrs to the game and haven't gotten a single drop, the animal mobs like the kungfu dugong on theres do drop it, but haven't gotten anything from bandits, pirates or marines.

**Comment by FGpisces** [comment]
The human mobs don't have their own drops, they mostly work like vanilla creatures, which very rarely drop some piece of armor they're wearing, or their weapon. And Marine captains are the only mobs that drop the capes, and they're still quite rare. And obviously, you can only get the maces and guns from the mobs who are actually holding those weapons.

**Comment by Erenussocrates** [comment]
Actually I used to play the previous versions and the mobs used to drop their weapons much more common, but I've yet to see that happen on the latest version as well. It's not even a rare occurance, it just doesn't happen anymore.

**Comment by Burningcory** [comment]
Also on the page of the mod pack, in the guide, the mob section isn't working, like it sends me back to the part where i decide which mod pack i wanna see. And just a little love cause i feel like there isn't enough appreciation, the work you guys have put in is insane and thank you so much.

**Comment by FGpisces** [comment]
We haven't changed anything about mob drops, they work on the vanilla code of dropping weapons and armor very rarely and damaged. If you're comparing 1.7.10 and 1.14, there's a difference in vanilla minecraft, but not in the mod.
And yes, the guide is heavily wip, we're working on it but slowly since there need to be made changes to the website, so it's not priority atm.
Glad you enjoy the mod <3
