### ISSUE TITLE
Some questions and suggestions 

### ISSUE THREAD

**Issue by Sircrocodile1** [PixelatedW/mineminenomi#87]
1. Could you add for the dehydration in sir crocodiles the wither effect. The effect will be removed if you come with water in contact
2. Can you make that i can combine the gura gura no mi and whitebeards biseto?

**Comment by Wynd** [comment]
Definitely not for 0.5.0 since the update is mostly done and any major changes can result in bugs...

- We'll discussion the wither effect thingy for crocodile's moves it'll be a pretty big buff and we need to balance it accordingly
- Sooner or later yeah this feature is planned not only with that weapon but being able to imbued the DF's power in other weapons (mostly swords obviously) as well

**Comment by FGpisces** [comment]
Cleaning up threads, suggestion has been noted, some Suna attacks already give wither, the weapon implementation with DFs will be added.
